name: backEnd server CD
on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  server-cd:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ 코드 체크아웃
        uses: actions/checkout@v3

      - name: 👻 노드 설정
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: 🏃‍♂️ Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USER}}
          key: ${{secrets.PEM_KEY}}
          port: ${{secrets.PORT}}
          script: |
            echo "${{secrets.ENV}}" > /home/ubuntu/WhereMyBus-BE/server/.env.prod
            bash /home/ubuntu/deploy.sh >> /dev/deploy.log 2>&1
